site_name: Documentación
use_directory_urls: false
nav:
- 'Principal':
  - 'Introducción':
    - 'Inicio': 'contents/intro/main.md'
- 'More':
  - 'Blog': 'https://www.esferatic.com'
  - 'Instagram': 'https://www.instagram.com/esferatic'

theme:
    language: es
    name: 'readthedocs'
    palette:
        primary: 'Teal'
        accent: 'Teal'
    font:
        text: Roboto
        code: Roboto Mono
    logo: 'images/floppy-ebenimeli.png'
    features:
      - content.code.annotate
plugins:
  - glightbox
  - search
  - mermaid2
  #- pandoc
  #pandoc:
  # - combined: true

markdown_extensions:
  - tables
  - attr_list
  - sane_lists
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
extra_css:
  - css/ict.css

extra_javascript:
  - https://unpkg.com/mermaid@10.2.4/dist/mermaid.min.js

